# Dockerfile-flask
# We simply inherit the Python 3 image. This image does
# not particularly care what OS runs underneath
FROM python:3
RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential
# Set an environment variable with the directory
# where we'll be running the app
ENV LOGIN /login
# Create the directory and instruct Docker to operate
# from there from now on
RUN mkdir $LOGIN
WORKDIR $LOGIN
# Expose the port uWSGI will listen on
#EXPOSE 5001
# Copy the requirements file in order to install
# Python dependencies
COPY requirements.txt .
# Install Python dependencies
RUN pip install -r requirements.txt
# We copy the rest of the codebase into the image
# we can optimize on this
#COPY login.py .
COPY login.py .
COPY apymongodb.py .
COPY app.py .
COPY bookapi.py .
COPY addorderapi.py .
# Finally, we run uWSGI with the ini file we
# created earlier
# TODO: We do not need uwsgi
#CMD [ "uwsgi", "--ini", "login.ini" ]

#COPY . /app
#WORKDIR /app
#RUN pip install -r requirements.txt
ENTRYPOINT ["python"]
CMD ["login.py"]
