# docker-compose.yml
version: '3'
services:
  flask:
    image: webapp-flask
    build:
      context: .
      dockerfile: Dockerfile-flask
    volumes:
      - ./conf.d:/etc/nginx/conf.d
  nginx:
    image: webapp-nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 5000:80
    depends_on:
      - flask
  mongodb:
    image: webapp-mongodb
    build:
      context: .
      dockerfile: Dockerfile-mongodb
    ports:
      - 27017:27017
  login-flask:
    image: webapp-login-flask
    build:
      context: .
      dockerfile: Dockerfile-login-flask
    volumes:
      - ./conf.d:/etc/nginx/conf.d
