FROM python:3

RUN apt-get update && apt-get install -y \
    mosquitto-clients \
    tcpdump \
    net-tools

# copy the iot5g.py file
ADD iotcloud.py /
ADD mylogger.py /

COPY requirements.txt /
RUN pip3 install -r requirements.txt

RUN chmod +x /iotcloud.py

# overwrite this with 'CMD []' in a dependent Dockerfile
CMD [ "python", "./iotcloud.py" ]
